x-generator: NSwag v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: MyApi
  version: 1.0.0
servers:
- url: http://localhost:5286
paths:
  /weatherforecast:
    get:
      tags:
      - WeatherForecast
      operationId: WeatherForecast_GetWeatherForecast
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherForecast'
components:
  schemas:
    WeatherForecast:
      type: object
      additionalProperties: false
      properties:
        Date:
          type: string
          format: date
        TemperatureC:
          type: integer
          format: int32
        Summary:
          type: string
          nullable: true
        TemperatureF:
          type: integer
          format: int32
